environment:
  collision_radius: 0.5
  dt: 0.1
  max_time: 100.0
player:
  position:
  - 0.0
  - 0.0
  - 0.0
  speed: 8.0
targets:
- id: 1
  max_flight_time: 15.4
  position:
  - -22.2
  - -2.6
  - 4.1
  trajectory_fn: 0.4 + 0.3*t*cos(0.9*t), 0.4 + 0.3*t*sin(0.9*t), 3.8
  velocity:
  - 0.0
  - 0.0
  - 0.0
- id: 2
  max_flight_time: 19.8
  position:
  - 4.3
  - 1.7
  - 5.9
  trajectory_fn: -1.8 + 6.3*cos(1.1*t), -0.8 + 6.3*sin(1.1*t), 7.6 + 0.7*t
  velocity:
  - 0.0
  - 0.0
  - 0.0
- id: 3
  max_flight_time: null
  position:
  - -15.2
  - 10.1
  - 6.6
  trajectory_fn: null
  velocity:
  - 2.7
  - -3.0
  - -1.5
