player:
  position:
  - 0.0
  - 0.0
  - 0.0
  speed: 10.0
environment:
  dt: 0.1
  max_time: 100.0
  collision_radius: 1.0
targets:
- id: 1
  position:
  - 10.0
  - 10.0
  - 10.0
  velocity:
  - 1.0
  - 0.0
  - 0.0
  trajectory_fn: null
  max_flight_time: 50.0
- id: 2
  position:
  - -10.0
  - 5.0
  - 0.0
  velocity:
  - 0.0
  - 1.0
  - 0.5
  trajectory_fn: null
  max_flight_time: 30.0
